### ISSUE TITLE
SERIOUS NAMING ISSUE

### ISSUE THREAD

**Issue by SamStudio8** [tomblanch118/Agatha#8]
EXCUSE ME BUT I THINK YOU'LL FIND THAT YOU SHOULD NAME THE TWO PROGRAMS THE OTHER WAY AROUND SUCH THAT YOU EXECUTE AGATHA BEFORE CHRISTIE

NOW YOUR SILLY JOKE IS RUINED BECAUSE YOUR PROGRAMS ARE EXECUTED IN THE ORDER CHRISTIE AGATHA

**Comment by SamStudio8** [comment]
(this is rly srs)

**Comment by tomblanch118** [comment]
NO
